/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sistema.view;

import com.pos.pojos.Usuario;
import java.beans.PropertyVetoException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Reynaldo
 */
public class vtnPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form vtnPrincipal
     */
    public static Usuario userlogin;// Clase que contiene al usuario logueado en el sistema

    public vtnPrincipal() {
        initComponents();
        userlogin = VtnLogin.user;//recibiendo el objeto usuario  de la ventana de logueqo
        labelUsuario.setText(userlogin.getNombres() + " " + userlogin.getApellidos());
        labelCargo.setText(userlogin.getCargo());
        if (userlogin.getTipousuario() == 1) {
            labelRolUser.setText("Vendedor");
            //Habilitar opciones de vendedor
            menuGestionUsers.setEnabled(false);

        }
        if (userlogin.getTipousuario() == 2) {
            //habilitar opciones de administrador
            labelRolUser.setText("Administrador");
        }
        if (userlogin.getTipousuario() == 3) {
            //habilitar los permisos para Super Usuario todos los persmisos
            labelRolUser.setText("Seper usuario");
        }

        //Maximizando la ventana principal
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMDI = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelCargo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelRolUser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuGestionUsers = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de ventas POS");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Usuario:");

        labelUsuario.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        labelUsuario.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Tipo usuario:");

        labelCargo.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        labelCargo.setText("jLabel3");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Rol usuario:");

        labelRolUser.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        labelRolUser.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(labelRolUser))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(labelUsuario))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelCargo)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelCargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelRolUser))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelMDILayout = new javax.swing.GroupLayout(panelMDI);
        panelMDI.setLayout(panelMDILayout);
        panelMDILayout.setHorizontalGroup(
            panelMDILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMDILayout.createSequentialGroup()
                .addContainerGap(532, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        panelMDILayout.setVerticalGroup(
            panelMDILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMDILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMDI.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(panelMDI, java.awt.BorderLayout.CENTER);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/images/OC.png"))); // NOI18N
        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        menuGestionUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/images/adduser.png"))); // NOI18N
        menuGestionUsers.setText("Usuarios");

        jMenuItem2.setText("Gestión de usuarios");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuGestionUsers.add(jMenuItem2);

        jMenuBar1.add(menuGestionUsers);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/iconos/almacen.png"))); // NOI18N
        jMenu2.setText("Almacen");

        jMenuItem1.setText("Gestion de almacen");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/images/producto2.png"))); // NOI18N
        jMenu3.setText("Productos");

        jMenuItem3.setText("Gestionar producto");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/images/Inventory-icon.png"))); // NOI18N
        jMenu4.setText("Inventario");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/iconos/menu/Notes.png"))); // NOI18N
        jMenuItem4.setText("Ingresar productos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/iconos/menu/file.png"))); // NOI18N
        jMenu7.setText("Operaciones inventario");

        jMenuItem8.setText("Ajustes ");
        jMenu7.add(jMenuItem8);

        jMenu4.add(jMenu7);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/images/ventas2.png"))); // NOI18N
        jMenu5.setText("Ventas");
        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/iconos/ajustes.png"))); // NOI18N
        jMenu6.setText("Configuración");

        jMenuItem5.setText("Parametros de sistema");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        String varValidacion = vtnAlmacen.validaVentana;
        if (varValidacion == null) {
            vtnAlmacen alm = new vtnAlmacen();
            alm.setTitle("Gestion de almacen..");
            alm.setResizable(false);//no es redimencionable
            alm.setMaximizable(false);//no se puede maximizar
            alm.setClosable(true);//si se puede cerra la ventana
            alm.setIconifiable(true);
            panelMDI.add(alm);
            alm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana gestión de almacen ya esta activa..!!", "Mensaje..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        String varValidacion = vtnUsuarios.validaVentana;
        if (varValidacion == null) {
            vtnUsuarios alm = new vtnUsuarios();
            alm.setTitle("Gestión de usuarios ");
            alm.setResizable(false);//no es redimencionable
            alm.setMaximizable(false);//no se puede maximizar
            alm.setClosable(true);//si se puede cerra la ventana
            alm.setIconifiable(true);
            panelMDI.add(alm);
            alm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana gestión de usuarios ya esta activa..!!", "Mensaje..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        try {
            String varValidacion = vtnProducto.validaVentana;
            if (varValidacion == null) {
                vtnProducto alm = new vtnProducto();
                alm.setTitle("Gestión de producto ");
                alm.setResizable(false);//no es redimencionable
                alm.setMaximizable(true);//no se puede maximizar
                alm.setClosable(true);//si se puede cerra la ventana
                alm.setIconifiable(true);
                //alm.setMaximum(true);
                panelMDI.add(alm);
                alm.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "La ventana gestión de productos ya esta activa..!!", "Mensaje..", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error" + ex.getMessage(), "Mensaje..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        try {
            String varValidacion = vtnAddProductoIngresoInventario.validaVentana;
            if (varValidacion == null) {
                vtnAddProductoIngresoInventario alm = new vtnAddProductoIngresoInventario();
                alm.setTitle("Ingreso almacen....:::: ");
                alm.setResizable(false);//no es redimencionable
                alm.setMaximizable(true);//no se puede maximizar
                alm.setClosable(true);//si se puede cerra la ventana
                alm.setIconifiable(true);
                //alm.setMaximum(true);
                panelMDI.add(alm);
                alm.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "La ventana ingreso a almacen ya esta activo..!!", "Mensaje..", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error" + ex.getMessage(), "Mensaje..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        String varValidacion = vtnParametrosSistema.validaVentana;
        if (varValidacion == null) {
            vtnParametrosSistema alm = new vtnParametrosSistema();
            alm.setTitle("Parametros del sistema..::..");
            alm.setResizable(false);//no es redimencionable
            alm.setMaximizable(false);//no se puede maximizar
            alm.setClosable(true);//si se puede cerra la ventana
            alm.setIconifiable(true);
            panelMDI.add(alm);
            alm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana ya esta activa..!!", "Mensaje..", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vtnPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelCargo;
    private javax.swing.JLabel labelRolUser;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JMenu menuGestionUsers;
    public static javax.swing.JDesktopPane panelMDI;
    // End of variables declaration//GEN-END:variables
}
